---
- name: Setup dotfiles
  hosts: localhost
  vars:
    dotfiles_dest: "{{ lookup('env','HOME') }}/git/dotfiles"
    home_dir: "{{ lookup('env','HOME') }}"
  tasks:
    - name: Copy nvim folder from dotfiles repository to ~/.config/nvim
      copy:
        src: "{{ dotfiles_dest }}/nvim/"
        dest: "{{ home_dir }}/.config/nvim/"
        remote_src: yes

    - name: Copy .tmux.conf from dotfiles to ~/.tmux.conf
      copy:
        src: "{{ dotfiles_dest }}/.tmux.conf"
        dest: "{{ home_dir }}/.tmux.conf"

    - name: Run PackerInstall for Neovim
      command: >
        nvim --headless -c "source {{ home_dir }}/.config/nvim/lua/shredder/packer.lua" -c "autocmd User PackerComplete quitall" -c "PackerInstall"
      args:
        creates: "{{ home_dir }}/.local/share/nvim/site/pack/packer"

    - name: Install tmux
      package:
        name: tmux
        state: present
      tags: tmux

    - name: Clone tmux-plugins/tpm repository
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ home_dir }}/.tmux/plugins/tpm"

    # without updating permissions of the cloned repo
    # you will not be able to install all of the tmux plugins
    # - name: Update TPM directory permissions
    #   file:
    #     path: "{{ home_dir }}/.tmux/plugins/tpm"
    #     mode: '0755'
    #     recurse: yes
    #
    - name: Install tmux plugins using TPM
      command: >
        {{ home_dir }}/.tmux/plugins/tpm/bin/install_plugins
      args:
        creates: "{{ home_dir }}/.tmux/plugins"
