- name: Setup dotfiles
  hosts: localhost
  become: yes
  vars:
    dotfiles_dest: "{{ lookup('env','HOME') }}/git/dotfiles"
  tasks:
    - name: Copy nvim folder from dotfiles repository to ~/.config/nvim
      copy:
        src: "{{ dotfiles_dest }}/nvim/"
        dest: "{{ lookup('env','HOME') }}/.config/nvim/"
        remote_src: yes

    - name: Create symbolic link for .tmux.conf
      file:
        src: "{{ dotfiles_dest }}/.tmux.conf"
        dest: "{{ lookup('env','HOME') }}/.tmux.conf"
        state: link
        force: yes

    - name: Run PackerInstall for Neovim
      command: >
        nvim --headless -c "source {{ lookup('env','HOME') }}/.config/nvim/lua/shredder/packer.lua" -c "autocmd User PackerComplete quitall" -c "PackerInstall"
      args:
        creates: "{{ lookup('env','HOME') }}/.local/share/nvim/site/pack/packer"
